import type { Product } from "./types"

export const products: Product[] = [
{
    id: "b7a5f9b2-0a2b-4d63-a1f7-7e35a5c3a001",
    name: "Digital Thermometer",
    slug: "digital-thermometer",
    description: "A reliable and fast digital thermometer for clinical temperature measurement.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Diagnostics",
    subcategory: null,
    ingredients: [],
    tags: ["thermometer", "temperature", "diagnostics", "hospital", "medical"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "c2b4a1d3-6e59-4f0a-845b-91a8c2d3a002",
    name: "Blood Pressure Monitor",
    slug: "blood-pressure-monitor",
    description: "Automatic digital blood pressure monitor for hospitals and home use.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Diagnostics",
    subcategory: null,
    ingredients: [],
    tags: ["bp monitor", "diagnostics", "vitals", "hospital", "medical equipment"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "d1c8b3e2-4a56-4b90-942a-2b8f3a4c0003",
    name: "Stethoscope",
    slug: "stethoscope",
    description: "High-quality acoustic stethoscope for clinical and hospital use.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Instruments",
    subcategory: null,
    ingredients: [],
    tags: ["stethoscope", "medical", "instrument", "diagnostics", "doctor"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "a9d3e5b1-0f47-4c82-91e2-f9c4b1f90004",
    name: "Hospital Bed",
    slug: "hospital-bed",
    description: "Adjustable hospital bed with side rails and comfortable mattress.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Furniture",
    subcategory: null,
    ingredients: [],
    tags: ["bed", "hospital furniture", "adjustable bed", "patient care"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "f7c2d8b3-9a41-43c5-8a21-0e5f2a3b0005",
    name: "Surgical Gloves",
    slug: "surgical-gloves",
    description: "Sterile latex surgical gloves providing superior tactile sensitivity.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "PPE",
    subcategory: null,
    ingredients: [],
    tags: ["gloves", "ppe", "surgical", "disposable", "latex"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "e2f5b7a4-3d6a-4f2b-9a77-3a7f8e9c0006",
    name: "Surgical Mask",
    slug: "surgical-mask",
    description: "Three-layer protective surgical mask for hospital use.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "PPE",
    subcategory: null,
    ingredients: [],
    tags: ["mask", "ppe", "surgery", "protection", "hospital"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "a4b2c9e1-6f5d-41f8-9e9a-5b3a7c2d0007",
    name: "Microscope",
    slug: "microscope",
    description: "Binocular compound microscope for laboratory and medical analysis.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Laboratory Equipment",
    subcategory: null,
    ingredients: [],
    tags: ["microscope", "laboratory", "analysis", "equipment", "medical"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "c3d1a9f2-5e4b-4d3a-b9a4-2c7d8a100008",
    name: "Centrifuge Machine",
    slug: "centrifuge-machine",
    description: "High-speed centrifuge for separating substances in laboratory samples.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Laboratory Equipment",
    subcategory: null,
    ingredients: [],
    tags: ["centrifuge", "lab equipment", "separation", "medical", "analysis"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "d8e1b2c3-7a9d-4c6f-b4a7-5f3e1b700009",
    name: "IV Stand",
    slug: "iv-stand",
    description: "Durable stainless steel IV stand with adjustable height and wheels.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Furniture",
    subcategory: null,
    ingredients: [],
    tags: ["iv stand", "furniture", "hospital", "infusion", "stainless steel"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "b2a3d9c8-5f4e-4b2a-83b7-1f3e9a100010",
    name: "Autoclave Sterilizer",
    slug: "autoclave-sterilizer",
    description: "Automatic steam sterilizer for hospital instruments and lab materials.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Laboratory Equipment",
    subcategory: null,
    ingredients: [],
    tags: ["autoclave", "sterilization", "equipment", "hospital", "lab"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
    {
    id: "e8c9a7f2-2b6d-4c3f-8b29-1a3f6a110011",
    name: "Blood Collection Tubes",
    slug: "blood-collection-tubes",
    description: "Vacuum-sealed tubes for safe and sterile blood sample collection.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Consumables",
    subcategory: null,
    ingredients: [],
    tags: ["blood", "collection", "lab", "vacutainer", "consumables"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "f1a3b7e4-4c5d-4d9a-8c3f-2b9e7a120012",
    name: "Disposable Syringes",
    slug: "disposable-syringes",
    description: "Sterile single-use syringes available in multiple sizes.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Consumables",
    subcategory: null,
    ingredients: [],
    tags: ["syringe", "injection", "disposable", "hospital", "medical"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "b3e7c8a1-7f2b-41c3-8b2f-6d4f9a130013",
    name: "Urine Test Strips",
    slug: "urine-test-strips",
    description: "Rapid urine analysis test strips for glucose, ketone, and protein detection.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Diagnostics",
    subcategory: null,
    ingredients: [],
    tags: ["urine test", "diagnostic", "strip", "lab", "analysis"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "c5a2e8d3-8b6c-45c9-b3a7-9e1b1c140014",
    name: "Hospital Wheelchair",
    slug: "hospital-wheelchair",
    description: "Durable foldable wheelchair designed for patient comfort and mobility.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Furniture",
    subcategory: null,
    ingredients: [],
    tags: ["wheelchair", "mobility", "furniture", "patient care"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "a4f8e7d9-1b3a-47b9-9d8b-5e9a1f150015",
    name: "Defibrillator",
    slug: "defibrillator",
    description: "Portable AED defibrillator for emergency cardiac resuscitation.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Medical Equipment",
    subcategory: null,
    ingredients: [],
    tags: ["defibrillator", "aed", "emergency", "medical device", "cardiac"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "f7d6a1b3-5c8f-4a9e-8b7d-4e1b1d160016",
    name: "Oxygen Concentrator",
    slug: "oxygen-concentrator",
    description: "Compact oxygen concentrator providing continuous oxygen flow for patients.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Medical Equipment",
    subcategory: null,
    ingredients: [],
    tags: ["oxygen", "concentrator", "respiratory", "equipment", "hospital"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "d2c3f1e4-8a9b-4b1a-9f4c-3a2b8a170017",
    name: "ECG Machine",
    slug: "ecg-machine",
    description: "12-lead electrocardiogram machine for accurate heart monitoring.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Diagnostics",
    subcategory: null,
    ingredients: [],
    tags: ["ecg", "diagnostic", "heart", "monitor", "hospital"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "b4a7d2f3-3c8e-4a6b-9e2d-2f9c1b180018",
    name: "Surgical Scissors",
    slug: "surgical-scissors",
    description: "Precision stainless steel scissors for surgical procedures.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Instruments",
    subcategory: null,
    ingredients: [],
    tags: ["scissors", "surgery", "instruments", "hospital"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "c1d8b3a9-7a4f-4b3c-b2a7-3a8f1c190019",
    name: "IV Cannula",
    slug: "iv-cannula",
    description: "Sterile IV cannula for intravenous therapy and fluid administration.",
    price: 1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Consumables",
    subcategory: null,
    ingredients: [],
    tags: ["iv", "cannula", "consumables", "medical", "infusion"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "a2f7e4b8-1a9c-4b6e-b1a4-9d4e1e200020",
    name: "Sterilization Pouch",
    slug: "sterilization-pouch",
    description: "Self-sealing sterilization pouch for safe instrument packaging.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Consumables",
    subcategory: null,
    ingredients: [],
    tags: ["sterilization", "pouch", "medical", "instruments", "packaging"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "e3c9b2a4-2a8d-4c7b-8b4f-1e3f7a210021",
    name: "Pipette Set",
    slug: "pipette-set",
    description: "Adjustable micropipette set with multiple volume options for lab use.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Laboratory Equipment",
    subcategory: null,
    ingredients: [],
    tags: ["pipette", "lab", "equipment", "liquid handling"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "d5f7c1a8-4b3e-47c6-b9a1-2c8e7a220022",
    name: "Test Tube Rack",
    slug: "test-tube-rack",
    description: "Durable polypropylene test tube rack with 50 tube capacity.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Laboratory Equipment",
    subcategory: null,
    ingredients: [],
    tags: ["test tube", "rack", "lab", "organization", "equipment"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "a8b2e1d9-5a7b-41c6-b8f3-4f9c7b230023",
    name: "Reagent Bottles",
    slug: "reagent-bottles",
    description: "Chemical-resistant glass bottles for storing reagents and solutions.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Reagents",
    subcategory: null,
    ingredients: [],
    tags: ["reagent", "bottle", "lab", "storage", "chemical"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "1a9f4d3b-6c8e-42e1-bb2d-12a34b5c6d7e",
    name: "Accurate HIV 1/2 Test Kit",
    slug: "accurate-hiv-test",
    description: "Reliable rapid diagnostic test for detecting HIV-1 and HIV-2 antibodies and antigen. Designed for quick screening with accurate results within minutes.",
    price: 150,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Medical Test Kits",
    subcategory: "Infectious Disease Test Kits",
    ingredients: [],
    tags: ["HIV", "diagnostic", "test", "medical", "kit"],
    usage: [
      { label: "Step 1", value: "Collect a blood or serum sample." },
      { label: "Step 2", value: "Add sample to the test strip as directed." },
      { label: "Step 3", value: "Wait for 15 minutes and read results." }
    ],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true
  },
  {
    id: "2b8e4c1a-9a0d-45b3-9d0e-23b45d6e7f8g",
    name: "Accurate HCV (Hepatitis C) Test Kit",
    slug: "accurate-hcv-test",
    description: "Rapid test for the qualitative detection of antibodies to Hepatitis C virus in human blood or serum. Provides results in minutes.",
    price: 150,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Medical Test Kits",
    subcategory: "Infectious Disease Test Kits",
    ingredients: [],
    tags: ["HCV", "hepatitis", "test", "diagnostic", "medical"],
    usage: [
      { label: "Step 1", value: "Collect blood or serum sample." },
      { label: "Step 2", value: "Apply to test cassette." },
      { label: "Step 3", value: "Wait for 10–15 minutes to read the result." }
    ],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true
  },
  {
    id: "3c7f5b2d-8d1f-4b8a-9e3c-67a89f1a2b3c",
    name: "Accurate TP (Syphilis) Test Kit",
    slug: "accurate-tp-test",
    description: "Accurate TP Syphilis Test Kit is a one-step rapid test for the detection of Treponema pallidum antibodies in human blood or serum.",
    price: 150,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Medical Test Kits",
    subcategory: "Infectious Disease Test Kits",
    ingredients: [],
    tags: ["syphilis", "TP", "test", "medical", "diagnostic"],
    usage: [
      { label: "Step 1", value: "Add sample to test area." },
      { label: "Step 2", value: "Wait for 10–15 minutes." },
      { label: "Step 3", value: "Check for lines indicating the result." }
    ],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true
  },
  {
    id: "4d6e7f2a-1b2c-4d8e-9a0b-8c7f5d6e4b3a",
    name: "Accurate HCG (Pregnancy) Test Kit",
    slug: "accurate-hcg-test",
    description: "One-step urine test for the qualitative detection of human chorionic gonadotropin (HCG) to determine early pregnancy.",
    price: 100,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Medical Test Kits",
    subcategory: "Pregnancy Test Kits",
    ingredients: [],
    tags: ["HCG", "pregnancy", "test", "urine", "kit"],
    usage: [
      { label: "Step 1", value: "Collect urine sample." },
      { label: "Step 2", value: "Dip test strip for a few seconds." },
      { label: "Step 3", value: "Read results within 5 minutes." }
    ],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true
  }
]
