import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Vitamin D3 1000IU Tablets",
    description: "High-strength Vitamin D3 tablets to support bone health, immune function, and muscle strength.",
    price:  1,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400",
    ],
    category: "Vitamins",
    ingredients: [
      "Vitamin D3 (Cholecalciferol)",
      "Microcrystalline Cellulose",
      "Vegetarian Capsule Shell",
      "No artificial colors or preservatives"
    ],
    tags: ["vitamin d", "bone health", "immune support", "muscle strength", "supplement", "d3"],
    usage: [
      { label: "Recommended Dosage", value: "Take 1-2 capsules daily with food" },
      { label: "Best Time", value: "Morning or as directed by your healthcare provider" },
      { label: "Storage", value: "Store in a cool, dry place away from direct sunlight" },
      { label: "Warning", value: "Consult your doctor before use if pregnant, nursing, or taking medications" }
    ],
    rating: 5,
    reviews: 234,
    featured: true,
    inStock: true,
  },
  {
    id: "2",
    name: "Omega-3 Fish Oil Capsules",
    description: "Premium omega-3 fish oil capsules for heart, brain, and eye health support.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400",
    ],
    category: "Supplements",
    ingredients: [],
    tags: ["omega-3", "fish oil", "heart health", "brain health", "eye health", "supplements"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "3",
    name: "Turmeric & Black Pepper Capsules",
    description: "Organic turmeric with black pepper extract for natural anti-inflammatory support.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Herbal",
    ingredients: [],
    tags: ["turmeric", "black pepper", "anti-inflammatory", "herbal", "joint health"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "4",
    name: "Collagen Beauty Powder",
    description: "Marine collagen powder to support skin elasticity, hair, and nail health.",
    price: 100,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Beauty",
    ingredients: [],
    tags: ["collagen", "beauty", "skin", "hair", "nails", "marine collagen"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "5",
    name: "Magnesium Glycinate 400mg",
    description: "Highly absorbable magnesium glycinate for muscle relaxation and better sleep.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Supplements",
    ingredients: [],
    tags: ["magnesium", "glycinate", "muscle relaxation", "sleep", "supplements"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "6",
    name: "Probiotics 50 Billion CFU",
    description: "Multi-strain probiotic supplement for digestive health and immune support.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Wellness",
    ingredients: [],
    tags: ["probiotics", "digestive health", "immune support", "gut health", "wellness"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "7",
    name: "Vitamin B Complex",
    description: "Complete B-vitamin complex for energy metabolism and nervous system support.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Vitamins",
    ingredients: [],
    tags: ["vitamin b", "b complex", "energy", "nervous system", "vitamins"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "8",
    name: "Ashwagandha Root Extract",
    description: "Adaptogenic herb extract to help manage stress and support overall well-being.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Herbal",
    ingredients: [],
    tags: ["ashwagandha", "adaptogen", "stress relief", "well-being", "herbal"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: true,
    inStock: true,
  },
  {
    id: "9",
    name: "Zinc Picolinate 15mg",
    description: "Highly bioavailable zinc supplement for immune system and skin health.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Supplements",
    ingredients: [],
    tags: ["zinc", "immune system", "skin health", "supplements", "picolinate"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "10",
    name: "Evening Primrose Oil",
    description: "Cold-pressed evening primrose oil capsules for hormonal balance and skin health.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Beauty",
    ingredients: [],
    tags: ["evening primrose oil", "hormonal balance", "skin health", "beauty", "epo"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "11",
    name: "Whey Protein Powder",
    description: "Premium whey protein isolate for muscle building and recovery.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Sports",
    ingredients: [],
    tags: ["whey protein", "muscle building", "recovery", "sports", "protein powder", "isolate"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "12",
    name: "Green Tea Extract",
    description: "Standardized green tea extract with EGCG for antioxidant support.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Herbal",
    ingredients: [],
    tags: ["green tea", "antioxidant", "egcg", "herbal", "extract"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "13",
    name: "Iron Bisglycinate 18mg",
    description: "Gentle iron supplement with superior absorption for energy and blood health.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Supplements",
    ingredients: [],
    tags: ["iron", "bisglycinate", "energy", "blood health", "supplements", "anemia"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "14",
    name: "Hyaluronic Acid Serum",
    description: "Pure hyaluronic acid serum for intense hydration and plump, youthful skin.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Beauty",
    ingredients: [],
    tags: ["hyaluronic acid", "serum", "hydration", "skin care", "anti-aging", "beauty"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "15",
    name: "Melatonin 3mg",
    description: "Natural sleep aid to help regulate sleep-wake cycles and improve sleep quality.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Wellness",
    ingredients: [],
    tags: ["melatonin", "sleep aid", "sleep quality", "insomnia", "wellness"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "16",
    name: "Calcium & Vitamin D3",
    description: "Combined calcium and vitamin D3 supplement for strong bones and teeth.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Vitamins",
    ingredients: [],
    tags: ["calcium", "vitamin d3", "bone health", "teeth health", "vitamins"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
  {
    id: "17",
    name: "Calcium",
    description: "Combined calcium and vitamin D3 supplement for strong bones and teeth.",
    price: 0,
    image: "/comingsoon.png?height=400&width=400",
    images: ["/image1.png?height=400&width=400","/image2.png?height=400&width=400","/image3.png?height=400&width=400"],
    category: "Proteins",
    ingredients: [],
    tags: ["calcium", "bone health", "minerals", "supplements"],
    usage: [],
    rating: 0,
    reviews: 0,
    featured: false,
    inStock: true,
  },
]
